#!/usr/bin/env bash
#checks for file

if [ -e ./school ]; then
	echo "school file exists"
	if [ $(wc -l < ./school) -eq 0 ];then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f ./school ]; then
		echo "school is a regular file"
	else
		echo ""
	fi
else
	echo "school file does not exist"
fi
